"""Added student_id field

Revision ID: c5b35a81fe77
Revises: 0340f6ef3de0
Create Date: 2024-03-10 11:10:22.048624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5b35a81fe77'
down_revision = '0340f6ef3de0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.String(length=64), nullable=True))
        batch_op.drop_index('ix_student_name')
        batch_op.create_index(batch_op.f('ix_student_name'), ['name'], unique=False)
        batch_op.create_unique_constraint(None, ['student_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_student_name'))
        batch_op.create_index('ix_student_name', ['name'], unique=True)
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###
